feat: [TKC-1616] Optimization of log and preparation for telemetry
kubeshop/testkube-cloud-charts pull request #132
Opened 2024-04-07 20:55 UTC by jmorante-ks

Draft PR including some improvements at the simple installer bash script:
- New log feature
- Improved user experience reducing logs and making them more user friendly
- Reorganized the code including some helper functions
- Limited some while-true loops to avoid infinite retries, aborting after a certain amount of attempts.

2024-04-09 14:39 UTC, jmorantebriones requested changes

2024-04-09 14:39 UTC, jmorantebriones commented on charts/testkube-enterprise/installer_enterprise.sh
We should launch the telemetry in background so it is not blocking the installation, as customers could have this URL blocked.

2024-04-09 14:44 UTC, jmorante-ks commented on charts/testkube-enterprise/installer_enterprise.sh
> +  curl -X POST "$TELEMETRY_URL" -H "'Content-Type: application/json'" -d "$json_payload" >> $LOG_FILE 2>&1
We should run this in background as I had originally, so it is not blocking the installation in case customers have segment blocked.

2024-04-10 09:28 UTC, ypoplavs approved these changes

2024-04-10 09:28 UTC, merged